version: '3.2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d/:ro
     - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
     - odoo
    read_only: true
    tmpfs:
     - /var/cache/nginx
     - /run
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      network:
        ipv4_address: 10.18.77.2

  odoo:
    build:
      context: ./odoo/
    restart: always
    volumes:
     - ./odoo/:/home/odoo/
     - ./odoo/odoo.conf:/etc/odoo/odoo.conf:ro
    depends_on:
     - postgres
    environment:
     - PGHOST=postgres
     - PGUSER=odoo
     - PGPASSWORD
    tmpfs:
     - /run
     - /tmp
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      network:
        ipv4_address: 10.18.77.3
        
  postgres:
    image: postgres:9.6-alpine
    restart: always
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=odoo
     - POSTGRES_PASSWORD
    tmpfs:
     - /run
     - /tmp
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    networks:
      network:
        ipv4_address: 10.18.77.4

  lerenew:
    image: certbot/certbot
    command: renew
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
    networks:
      network:
        ipv4_address: 10.18.77.5

networks:
  network:
    ipam:
      driver: default
      config:
      -
        subnet: 10.18.77.0/24
